fix: improve canvas clearing in inspect state machine
aidenybai/react-scan pull request #65
Opened 2024-12-02 19:03 UTC by pivanov

This change provides a more reliable solution for canvas clearing when transitioning between inspection states, preventing artifacts and improving performance.

2024-12-03 03:53 UTC, RobPruzan commented on packages/scan/src/core/web/inspect-element/inspect-state-machine.ts
> -            };
This was a weird case that I didn't do enough investigation on, so there is a root fix possible. But, the reproduction for the original problem that motivated this code was:

- move your mouse continuously while inspecting
- click escape (cancels the inspection)  and keep moving your mouse
- inspect overlay stays drawn on canvas

Testing this branch, the problem does come back. The best solution here would be figuring out which of the following cases is happening:
- the "inspecting" mouse move handler is not being cleaned up correctly, and drawing to screen during inspect-off
- some browser priority thing with how event handlers run in what order (queued mousemoves with stale closures?) 
  -  I don't think its this because we guard against that ` const mouseMove = throttle((e: MouseEvent) => {
              if (ReactScanInternals.inspectState.kind !== 'inspecting') {
                return;
              }`
 - we are clearing canvas wrong (something to do with how the canvas is transformed)
 - something else?

2024-12-03 03:54 UTC, RobPruzan requested changes
Here is the reproduction of the issue I mentioned in the review comment:
https://github.com/user-attachments/assets/2cb151c1-888e-47af-a643-f9dc4cd931aa

2024-12-03 03:54 UTC, RobPruzan commented on packages/scan/src/core/web/inspect-element/inspect-state-machine.ts
> -            };
This was a weird case that I didn't do enough investigation on, so there is a root fix possible. But, the reproduction for the original problem that motivated this code was:

- move your mouse continuously while inspecting
- click escape (cancels the inspection)  and keep moving your mouse
- inspect overlay stays drawn on canvas

Testing this branch, the problem does come back. The best solution here would be figuring out which of the following cases is happening:
- the "inspecting" mouse move handler is not being cleaned up correctly, and drawing to screen during inspect-off
- some browser priority thing with how event handlers run in what order (queued mousemoves with stale closures?) 
  -  I don't think its this because we guard against that ` const mouseMove = throttle((e: MouseEvent) => {
              if (ReactScanInternals.inspectState.kind !== 'inspecting') {
                return;
              }`
 - we are clearing canvas wrong (something to do with how the canvas is transformed)
 - something else?

2024-12-03 16:03 UTC, pivanov commented on packages/scan/src/core/web/inspect-element/inspect-state-machine.ts
> -            };
Thank you for pointing this out 🚀

I’ve made the following changes to address the problem:
1. **Proper Cleanup of Animation Frames**:
   - Added an `isActive` flag in `recursiveRaf` to ensure that no stale animation frames continue running when transitioning to `inspect-off`.
   - Explicitly cancel the pending animation frame using `cancelAnimationFrame` when the state changes.

2. **Immediate Canvas Clearing**:
   - Ensured `clearCanvas()` is called immediately when transitioning to `inspect-off`, fixing the issue of the overlay remaining visible.

3. **Removed Unnecessary Hack**:
   - Removed the `mousemove`-based hack for clearing and resizing the canvas, as the root cause is addressed with proper cleanup.

4. **Event Handlers and State Cleanup**:
   - Used `unsubscribeAll()` to ensure all mouse-related event handlers and recursive RAF calls are unsubscribed when transitioning out of `inspecting` or `focused` states.
   - Reset `lastHoveredElement` to `undefined` to avoid stale references to DOM elements.

These changes should prevent the canvas overlay from persisting after `inspect-off` is triggered, ensuring proper state transitions.

Let me know if there’s anything I missed or further improvements you’d suggest!

2024-12-26 07:50 UTC, pivanov commented
This one is obsolate now :)

2024-12-26 07:50 UTC, closed without merging